#!/usr/bin/env python3
# Copyright (c) 2022 FRC Team 1678: Citrus Circuits
from cmath import exp
import pytest
from unittest.mock import patch
from calculations import obj_team
from server import Server


@pytest.mark.clouddb
class TestOBJTeamCalc:
    def setup_method(self, method):
        with patch("server.Server.ask_calc_all_data", return_value=False):
            self.test_server = Server()
        self.test_calc = obj_team.OBJTeamCalc(self.test_server)

    def test___init__(self):
        """Test if attributes are set correctly"""
        assert self.test_calc.watched_collections == ["obj_tim", "subj_tim"]
        assert self.test_calc.server == self.test_server

    def test_averages(self):
        """Tests calculate_averages function from src/calculations/obj_team.py"""
        tims = [
            {
                "match_number": 2,
                "auto_cone_high": 2,
                "auto_cone_mid": 1,
                "auto_cone_low": 14,
                "auto_total_cones": 17,
                "auto_cube_high": 5,
                "auto_cube_mid": 6,
                "auto_cube_low": 18,
                "auto_total_cubes": 29,
                "tele_cone_high": 5,
                "tele_cone_mid": 10,
                "tele_cone_low": 1,
                "tele_total_cones": 16,
                "tele_cube_high": 10,
                "tele_cube_mid": 6,
                "tele_cube_low": 4,
                "tele_total_cubes": 20,
                "incap": 20,
                "intakes_ground": 20,
                "intakes_station": 6,
                "intakes_low_row": 10,
                "total_intakes": 36,
                "tele_total_gamepieces_low": 5,
                "tele_total_gamepieces": 36,
                "auto_total_gamepieces_low": 32,
                "auto_total_gamepieces": 46,
                "failed_scores": 5,
            },
            {
                "match_number": 4,
                "auto_cone_high": 6,
                "auto_cone_mid": 8,
                "auto_cone_low": 10,
                "auto_total_cones": 24,
                "auto_cube_high": 10,
                "auto_cube_mid": 9,
                "auto_cube_low": 4,
                "auto_total_cubes": 23,
                "tele_cone_high": 6,
                "tele_cone_mid": 8,
                "tele_cone_low": 14,
                "tele_total_cones": 28,
                "tele_cube_high": 10,
                "tele_cube_mid": 4,
                "tele_cube_low": 3,
                "tele_total_cubes": 17,
                "incap": 90,
                "intakes_ground": 30,
                "intakes_station": 20,
                "intakes_low_row": 22,
                "total_intakes": 72,
                "tele_total_gamepieces_low": 17,
                "tele_total_gamepieces": 45,
                "auto_total_gamepieces_low": 14,
                "auto_total_gamepieces": 47,
                "failed_scores": 10,
            },
            {
                "match_number": 5,
                "auto_cone_high": 1,
                "auto_cone_mid": 1,
                "auto_cone_low": 2,
                "auto_total_cones": 4,
                "auto_cube_high": 3,
                "auto_cube_mid": 2,
                "auto_cube_low": 4,
                "auto_total_cubes": 9,
                "tele_cone_high": 1,
                "tele_cone_mid": 4,
                "tele_cone_low": 2,
                "tele_total_cones": 7,
                "tele_cube_high": 3,
                "tele_cube_mid": 2,
                "tele_cube_low": 1,
                "tele_total_cubes": 6,
                "incap": 4,
                "intakes_ground": 5,
                "intakes_station": 10,
                "intakes_low_row": 2,
                "total_intakes": 17,
                "tele_total_gamepieces_low": 3,
                "tele_total_gamepieces": 13,
                "auto_total_gamepieces_low": 6,
                "auto_total_gamepieces": 13,
                "failed_scores": 15,
            },
            {
                "match_number": 3,
                "auto_cone_high": 6,
                "auto_cone_mid": 4,
                "auto_cone_low": 2,
                "auto_total_cones": 12,
                "auto_cube_high": 8,
                "auto_cube_mid": 3,
                "auto_cube_low": 4,
                "auto_total_cubes": 15,
                "tele_cone_high": 2,
                "tele_cone_mid": 8,
                "tele_cone_low": 3,
                "tele_total_cones": 13,
                "tele_cube_high": 2,
                "tele_cube_mid": 4,
                "tele_cube_low": 9,
                "tele_total_cubes": 15,
                "incap": 24,
                "intakes_ground": 9,
                "intakes_station": 4,
                "intakes_low_row": 10,
                "total_intakes": 23,
                "tele_total_gamepieces_low": 12,
                "tele_total_gamepieces": 28,
                "auto_total_gamepieces_low": 6,
                "auto_total_gamepieces": 27,
                "failed_scores": 15,
            },
            {
                "match_number": 1,
                "auto_cone_high": 8,
                "auto_cone_mid": 3,
                "auto_cone_low": 4,
                "auto_total_cones": 15,
                "auto_cube_high": 1,
                "auto_cube_mid": 8,
                "auto_cube_low": 4,
                "auto_total_cubes": 13,
                "tele_cone_high": 4,
                "tele_cone_mid": 2,
                "tele_cone_low": 8,
                "tele_total_cones": 14,
                "tele_cube_high": 2,
                "tele_cube_mid": 3,
                "tele_cube_low": 5,
                "tele_total_cubes": 10,
                "incap": 32,
                "intakes_ground": 10,
                "intakes_station": 4,
                "intakes_low_row": 5,
                "total_intakes": 19,
                "tele_total_gamepieces_low": 13,
                "tele_total_gamepieces": 24,
                "auto_total_gamepieces_low": 8,
                "auto_total_gamepieces": 28,
                "failed_scores": 5,
            },
        ]

        expected_output = {
            "auto_avg_cone_high": 4.6,
            "auto_avg_cone_mid": 3.4,
            "auto_avg_cone_low": 6.4,
            "auto_avg_cone_total": 14.4,
            "auto_avg_cube_high": 5.4,
            "auto_avg_cube_mid": 5.6,
            "auto_avg_cube_low": 6.8,
            "auto_avg_cube_total": 17.8,
            "tele_avg_cone_high": 3.6,
            "tele_avg_cone_mid": 6.4,
            "tele_avg_cone_low": 5.6,
            "tele_avg_cone_total": 15.6,
            "tele_avg_cube_high": 5.4,
            "tele_avg_cube_mid": 3.8,
            "tele_avg_cube_low": 4.4,
            "tele_avg_cube_total": 13.6,
            "avg_incap_time": 34.0,
            "avg_intakes_ground": 14.8,
            "avg_intakes_station": 8.8,
            "avg_intakes_low_row": 9.8,
            "avg_total_intakes": 33.4,
            "tele_avg_gamepieces_low": 10.0,
            "auto_avg_gamepieces_low": 13.2,
            "auto_avg_gamepieces": 32.2,
            "tele_avg_gamepieces": 29.2,
            "avg_failed_scores": 10,
            "lfm_auto_avg_cone_high": 3.75,
            "lfm_auto_avg_cone_mid": 3.5,
            "lfm_auto_avg_cone_low": 7.0,
            "lfm_auto_avg_cone_total": 14.25,
            "lfm_auto_avg_cube_high": 6.5,
            "lfm_auto_avg_cube_mid": 5.0,
            "lfm_auto_avg_cube_low": 7.5,
            "lfm_auto_avg_cube_total": 19.0,
            "lfm_tele_avg_cone_high": 3.5,
            "lfm_tele_avg_cone_mid": 7.5,
            "lfm_tele_avg_cone_low": 5.0,
            "lfm_tele_avg_cone_total": 16.0,
            "lfm_tele_avg_cube_high": 6.25,
            "lfm_tele_avg_cube_mid": 4.0,
            "lfm_tele_avg_cube_low": 4.25,
            "lfm_tele_avg_cube_total": 14.5,
            "lfm_auto_avg_gamepieces": 33.25,
            "lfm_tele_avg_gamepieces": 30.5,
            "lfm_tele_avg_gamepieces_low": 9.25,
            "lfm_auto_avg_gamepieces_low": 14.5,
            "lfm_avg_incap_time": 34.5,
            "lfm_avg_intakes_ground": 16.0,
            "lfm_avg_intakes_station": 10.0,
            "lfm_avg_intakes_low_row": 11.0,
            "lfm_avg_total_intakes": 37.0,
            "lfm_avg_failed_scores": 11.25,
        }
        lfm_tims = [tim for tim in tims if tim["match_number"] > 1]
        action_counts = self.test_calc.get_action_counts(tims)
        lfm_action_counts = self.test_calc.get_action_counts(lfm_tims)
        assert (
            self.test_calc.calculate_averages(action_counts, lfm_action_counts) == expected_output
        )

    def test_standard_deviations(self):
        """Tests calculate_standard_deviations function from src/calculations/obj_team.py"""
        tims = [
            {
                "match_number": 1,
                "auto_cone_high": 2,
                "auto_cone_mid": 1,
                "auto_cone_low": 14,
                "auto_total_cones": 17,
                "auto_cube_high": 5,
                "auto_cube_mid": 6,
                "auto_cube_low": 18,
                "auto_total_cubes": 29,
                "tele_cone_high": 5,
                "tele_cone_mid": 10,
                "tele_cone_low": 1,
                "tele_total_cones": 16,
                "tele_cube_high": 10,
                "tele_cube_mid": 6,
                "tele_cube_low": 4,
                "tele_total_cubes": 20,
                "incap": 20,
                "intakes_ground": 20,
                "intakes_station": 6,
                "intakes_low_row": 10,
                "total_intakes": 36,
                "tele_total_gamepieces_low": 5,
                "tele_total_gamepieces": 36,
                "auto_total_gamepieces_low": 32,
                "auto_total_gamepieces": 46,
                "failed_scores": 3,
            },
            {
                "match_number": 2,
                "auto_cone_high": 6,
                "auto_cone_mid": 8,
                "auto_cone_low": 10,
                "auto_total_cones": 24,
                "auto_cube_high": 10,
                "auto_cube_mid": 9,
                "auto_cube_low": 4,
                "auto_total_cubes": 23,
                "tele_cone_high": 6,
                "tele_cone_mid": 8,
                "tele_cone_low": 14,
                "tele_total_cones": 28,
                "tele_cube_high": 10,
                "tele_cube_mid": 4,
                "tele_cube_low": 3,
                "tele_total_cubes": 17,
                "incap": 90,
                "intakes_ground": 30,
                "intakes_station": 20,
                "intakes_low_row": 22,
                "total_intakes": 72,
                "tele_total_gamepieces_low": 17,
                "tele_total_gamepieces": 45,
                "auto_total_gamepieces_low": 14,
                "auto_total_gamepieces": 47,
                "failed_scores": 2,
            },
            {
                "match_number": 3,
                "auto_cone_high": 8,
                "auto_cone_mid": 3,
                "auto_cone_low": 4,
                "auto_total_cones": 15,
                "auto_cube_high": 1,
                "auto_cube_mid": 8,
                "auto_cube_low": 4,
                "auto_total_cubes": 13,
                "tele_cone_high": 4,
                "tele_cone_mid": 2,
                "tele_cone_low": 8,
                "tele_total_cones": 14,
                "tele_cube_high": 2,
                "tele_cube_mid": 3,
                "tele_cube_low": 5,
                "tele_total_cubes": 10,
                "incap": 32,
                "intakes_ground": 10,
                "intakes_station": 4,
                "intakes_low_row": 5,
                "total_intakes": 19,
                "tele_total_gamepieces_low": 13,
                "tele_total_gamepieces": 24,
                "auto_total_gamepieces_low": 8,
                "auto_total_gamepieces": 28,
                "failed_scores": 0,
            },
        ]

        expected_output = {
            "auto_sd_cone_high": 2.494438257849294,
            "auto_sd_cone_mid": 2.943920288775949,
            "auto_sd_cone_low": 4.109609335312651,
            "auto_sd_cone_total": 3.858612300930075,
            "auto_sd_cube_high": 3.681787005729087,
            "auto_sd_cube_mid": 1.247219128924647,
            "auto_sd_cube_low": 6.599663291074443,
            "auto_sd_cube_total": 6.599663291074443,
            "tele_sd_cone_high": 0.816496580927726,
            "tele_sd_cone_mid": 3.39934634239519,
            "tele_sd_cone_low": 5.312459150169742,
            "tele_sd_cone_total": 6.182412330330469,
            "tele_sd_cube_high": 3.7712361663282534,
            "tele_sd_cube_mid": 1.247219128924647,
            "tele_sd_cube_low": 0.816496580927726,
            "tele_sd_cube_total": 4.189935029992179,
            "auto_sd_gamepieces": 8.73053390247253,
            "tele_sd_gamepieces": 8.602325267042627,
        }
        action_counts = self.test_calc.get_action_counts(tims)
        assert self.test_calc.calculate_standard_deviations(action_counts) == expected_output

    def test_counts(self):
        """Tests calculate_counts function from src/calculations/obj_team.py"""
        tims = [
            {
                "start_position": "1",
                "auto_charge_attempt": 1,
                "auto_charge_level": "ENGAGE",
                "tele_charge_attempt": 1,
                "tele_charge_level": "PARK",
                "match_number": 1,
                "incap": 2,
            },
            {
                "start_position": "2",
                "auto_charge_attempt": 1,
                "auto_charge_level": "DOCK",
                "tele_charge_attempt": 1,
                "tele_charge_level": "ENGAGE",
                "match_number": 4,
                "incap": 5,
            },
            {
                "start_position": "3",
                "auto_charge_attempt": 1,
                "auto_charge_level": "ENGAGE",
                "tele_charge_attempt": 1,
                "tele_charge_level": "DOCK",
                "match_number": 3,
                "incap": 2,
            },
            {
                "start_position": "4",
                "auto_charge_attempt": 0,
                "auto_charge_level": "NONE",
                "tele_charge_attempt": 1,
                "tele_charge_level": "PARK",
                "match_number": 2,
                "incap": 0,
            },
            {
                "start_position": "0",
                "auto_charge_attempt": 1,
                "auto_charge_level": "ENGAGE",
                "tele_charge_attempt": 0,
                "tele_charge_level": "NONE",
                "match_number": 5,
                "incap": 0,
            },
        ]
        lfm_tims = [tim for tim in tims if tim["match_number"] > 1]

        expected_output = {
            "auto_charge_attempts": 4,
            "auto_dock_successes": 1,
            "auto_engage_successes": 3,
            "tele_charge_attempts": 4,
            "tele_dock_successes": 1,
            "tele_engage_successes": 1,
            "tele_park_successes": 2,
            "position_zero_starts": 1,
            "position_one_starts": 1,
            "position_two_starts": 1,
            "position_three_starts": 1,
            "position_four_starts": 1,
            "matches_incap": 3,
            "matches_played": 5,
            "lfm_auto_charge_attempts": 3,
            "lfm_auto_dock_successes": 1,
            "lfm_auto_engage_successes": 2,
            "lfm_tele_charge_attempts": 3,
            "lfm_tele_dock_successes": 1,
            "lfm_tele_engage_successes": 1,
            "lfm_tele_park_successes": 1,
            "lfm_position_zero_starts": 1,
            "lfm_position_one_starts": 0,
            "lfm_position_two_starts": 1,
            "lfm_position_three_starts": 1,
            "lfm_position_four_starts": 1,
            "lfm_matches_incap": 2,
        }
        assert self.test_calc.calculate_counts(tims, lfm_tims) == expected_output

    def test_super_counts(self):
        """Tests calculate_super_counts function from src/calculations.obj_team.py"""
        tims = [
            {"match_number": 1, "team_number": "1678", "scored_coop": True, "played_defense": True},
            {
                "match_number": 2,
                "team_number": "1678",
                "scored_coop": False,
                "played_defense": True,
            },
            {
                "match_number": 3,
                "team_number": "1678",
                "scored_coop": True,
                "played_defense": False,
            },
        ]
        expected_output = {"matches_scored_coop": 2, "matches_played_defense": 2}
        assert self.test_calc.calculate_super_counts(tims) == expected_output

    def test_extrema(self):
        tims = [
            {
                "preloaded_gamepiece": "CONE",
                "auto_cone_high": 7,
                "auto_cone_mid": 6,
                "auto_cone_low": 3,
                "auto_total_cones": 16,
                "auto_cube_high": 5,
                "auto_cube_mid": 6,
                "auto_cube_low": 8,
                "auto_total_cubes": 19,
                "tele_cone_high": 9,
                "tele_cone_mid": 20,
                "tele_cone_low": 2,
                "tele_total_cones": 31,
                "tele_cube_high": 5,
                "tele_cube_mid": 4,
                "tele_cube_low": 11,
                "tele_total_cubes": 20,
                "intakes_ground": 15,
                "intakes_station": 4,
                "intakes_low_row": 1,
                "total_intakes": 20,
                "incap": 11,
                "auto_charge_level": "DOCK",
                "tele_charge_level": "PARK",
                "match_number": 1,
                "start_position": 1,
                "tele_total_gamepieces_low": 13,
                "tele_total_gamepieces": 51,
                "auto_total_gamepieces_low": 11,
                "auto_total_gamepieces": 1,
                "failed_scores": 3,
            },
            {
                "preloaded_gamepiece": "CONE",
                "auto_cone_high": 4,
                "auto_cone_mid": 3,
                "auto_cone_low": 8,
                "auto_total_cones": 15,
                "auto_cube_high": 11,
                "auto_cube_mid": 2,
                "auto_cube_low": 9,
                "auto_total_cubes": 22,
                "tele_cone_high": 1,
                "tele_cone_mid": 2,
                "tele_cone_low": 3,
                "tele_total_cones": 6,
                "tele_cube_high": 3,
                "tele_cube_mid": 2,
                "tele_cube_low": 7,
                "tele_total_cubes": 12,
                "intakes_ground": 12,
                "intakes_station": 17,
                "intakes_low_row": 5,
                "total_intakes": 34,
                "incap": 20,
                "auto_charge_level": "DOCK",
                "tele_charge_level": "ENGAGE",
                "match_number": 2,
                "start_position": 2,
                "tele_total_gamepieces_low": 10,
                "tele_total_gamepieces": 18,
                "auto_total_gamepieces_low": 17,
                "auto_total_gamepieces": 20,
                "failed_scores": 4,
            },
            {
                "preloaded_gamepiece": "CONE",
                "auto_cone_high": 4,
                "auto_cone_mid": 10,
                "auto_cone_low": 9,
                "auto_total_cones": 23,
                "auto_cube_high": 10,
                "auto_cube_mid": 2,
                "auto_cube_low": 4,
                "auto_total_cubes": 16,
                "tele_cone_high": 1,
                "tele_cone_mid": 12,
                "tele_cone_low": 3,
                "tele_total_cones": 16,
                "tele_cube_high": 2,
                "tele_cube_mid": 9,
                "tele_cube_low": 4,
                "tele_total_cubes": 15,
                "intakes_ground": 4,
                "intakes_station": 6,
                "intakes_low_row": 20,
                "total_intakes": 30,
                "incap": 10,
                "auto_charge_level": "DOCK",
                "tele_charge_level": "DOCK",
                "match_number": 3,
                "start_position": 1,
                "tele_total_gamepieces_low": 7,
                "tele_total_gamepieces": 31,
                "auto_total_gamepieces_low": 13,
                "auto_total_gamepieces": 63,
                "failed_scores": 2,
            },
            {
                "preloaded_gamepiece": "CONE",
                "auto_cone_high": 9,
                "auto_cone_mid": 4,
                "auto_cone_low": 2,
                "auto_total_cones": 15,
                "auto_cube_high": 4,
                "auto_cube_mid": 2,
                "auto_cube_low": 3,
                "auto_total_cubes": 9,
                "tele_cone_high": 2,
                "tele_cone_mid": 4,
                "tele_cone_low": 7,
                "tele_total_cones": 13,
                "tele_cube_high": 2,
                "tele_cube_mid": 1,
                "tele_cube_low": 4,
                "tele_total_cubes": 7,
                "intakes_ground": 1,
                "intakes_station": 7,
                "intakes_low_row": 1,
                "total_intakes": 9,
                "incap": 3,
                "auto_charge_level": "ENGAGE",
                "tele_charge_level": "DOCK",
                "match_number": 4,
                "start_position": 4,
                "tele_total_gamepieces_low": 11,
                "tele_total_gamepieces": 20,
                "auto_total_gamepieces_low": 5,
                "auto_total_gamepieces": 1,
                "failed_scores": 4,
            },
            {
                "preloaded_gamepiece": "CONE",
                "auto_cone_high": 1,
                "auto_cone_mid": 5,
                "auto_cone_low": 10,
                "auto_total_cones": 16,
                "auto_cube_high": 2,
                "auto_cube_mid": 9,
                "auto_cube_low": 3,
                "auto_total_cubes": 14,
                "tele_cone_high": 8,
                "tele_cone_mid": 6,
                "tele_cone_low": 8,
                "tele_total_cones": 22,
                "tele_cube_high": 1,
                "tele_cube_mid": 3,
                "tele_cube_low": 8,
                "tele_total_cubes": 12,
                "intakes_ground": 3,
                "intakes_station": 8,
                "intakes_low_row": 10,
                "total_intakes": 21,
                "incap": 90,
                "auto_charge_level": "DOCK",
                "tele_charge_level": "ENGAGE",
                "match_number": 5,
                "start_position": 1,
                "tele_total_gamepieces_low": 16,
                "tele_total_gamepieces": 34,
                "auto_total_gamepieces_low": 13,
                "auto_total_gamepieces": 4,
                "failed_scores": 3,
            },
        ]
        lfm_tims = [tim for tim in tims if tim["match_number"] > 1]
        action_counts = self.test_calc.get_action_counts(tims)
        lfm_action_counts = self.test_calc.get_action_counts(lfm_tims)
        action_categories = self.test_calc.get_action_categories(tims)
        lfm_action_categories = self.test_calc.get_action_categories(lfm_tims)
        expected_output = {
            "auto_max_cone_high": 9,
            "auto_max_cone_mid": 10,
            "auto_max_cone_low": 10,
            "auto_max_cones": 23,
            "auto_max_cube_high": 11,
            "auto_max_cube_mid": 9,
            "auto_max_cube_low": 9,
            "auto_max_cubes": 22,
            "tele_max_cone_high": 9,
            "tele_max_cone_mid": 20,
            "tele_max_cone_low": 8,
            "tele_max_cones": 31,
            "tele_max_cube_high": 5,
            "tele_max_cube_mid": 9,
            "tele_max_cube_low": 11,
            "tele_max_cubes": 20,
            "auto_max_gamepieces": 63,
            "tele_max_gamepieces": 51,
            "max_incap": 90,
            "max_auto_charge_level": "ENGAGE",
            "max_tele_charge_level": "ENGAGE",
            "lfm_auto_max_cone_high": 9,
            "lfm_auto_max_cone_mid": 10,
            "lfm_auto_max_cone_low": 10,
            "lfm_auto_max_cones": 23,
            "lfm_auto_max_cube_high": 11,
            "lfm_auto_max_cube_mid": 9,
            "lfm_auto_max_cube_low": 9,
            "lfm_auto_max_cubes": 22,
            "lfm_tele_max_cone_high": 8,
            "lfm_tele_max_cone_mid": 12,
            "lfm_tele_max_cone_low": 8,
            "lfm_tele_max_cones": 22,
            "lfm_tele_max_cube_high": 3,
            "lfm_tele_max_cube_mid": 9,
            "lfm_tele_max_cube_low": 8,
            "lfm_tele_max_cubes": 15,
            "lfm_auto_max_gamepieces": 63,
            "lfm_tele_max_gamepieces": 34,
            "lfm_max_incap": 90,
            "lfm_max_auto_charge_level": "ENGAGE",
            "lfm_max_tele_charge_level": "ENGAGE",
        }
        assert (
            self.test_calc.calculate_extrema(
                action_counts,
                lfm_action_counts,
                action_categories,
                lfm_action_categories,
            )
            == expected_output
        )

    def test_medians(self):
        tims = [
            {"match_number": 1, "incap": 30},
            {"match_number": 2, "incap": 49},
            {"match_number": 3, "incap": 60},
            {"match_number": 4, "incap": 120},
            {"match_number": 5, "incap": 130},
        ]

        expected_output = {
            "median_incap": 60,
            "lfm_median_incap": 90,
        }

        lfm_tims = [tim for tim in tims if tim["match_number"] > 1]
        action_sum = self.test_calc.get_action_sum(tims)
        lfm_action_sum = self.test_calc.get_action_sum(lfm_tims)
        assert (
            self.test_calc.calculate_medians(
                action_sum,
                lfm_action_sum,
            )
        ) == expected_output

    def test_modes(self):
        tims = [
            {
                "match_number": 1,
                "preloaded_gamepiece": "CONE",
                "auto_charge_level": "ENGAGE",
                "tele_charge_level": "DOCK",
                "start_position": "1",
            },
            {
                "match_number": 2,
                "preloaded_gamepiece": "CUBE",
                "auto_charge_level": "ENGAGE",
                "tele_charge_level": "PARK",
                "start_position": "2",
            },
            {
                "match_number": 3,
                "preloaded_gamepiece": "CONE",
                "auto_charge_level": "DOCK",
                "tele_charge_level": "DOCK",
                "start_position": "3",
            },
            {
                "match_number": 4,
                "preloaded_gamepiece": "CONE",
                "auto_charge_level": "DOCK",
                "tele_charge_level": "ENGAGE",
                "start_position": "1",
            },
            {
                "match_number": 5,
                "preloaded_gamepiece": "CUBE",
                "auto_charge_level": "ENGAGE",
                "tele_charge_level": "ENGAGE",
                "start_position": "2",
            },
            {
                "match_number": 6,
                "preloaded_gamepiece": "CUBE",
                "auto_charge_level": "DOCK",
                "tele_charge_level": "DOCK",
                "start_position": "3",
            },
            {
                "match_number": 7,
                "preloaded_gamepiece": "CUBE",
                "auto_charge_level": "DOCK",
                "tele_charge_level": "PARK",
                "start_position": "0",
            },
            {
                "match_number": 8,
                "preloaded_gamepiece": "CONE",
                "auto_charge_level": "DOCK",
                "tele_charge_level": "PARK",
                "start_position": "0",
            },
            {
                "match_number": 9,
                "preloaded_gamepiece": "CONE",
                "auto_charge_level": "ENGAGE",
                "tele_charge_level": "ENGAGE",
                "start_position": "0",
            },
            {
                "match_number": 10,
                "preloaded_gamepiece": "CONE",
                "auto_charge_level": "DOCK",
                "tele_charge_level": "DOCK",
                "start_position": "0",
            },
            {
                "match_number": 11,
                "preloaded_gamepiece": "CUBE",
                "auto_charge_level": "ENGAGE",
                "tele_charge_level": "DOCK",
                "start_position": "0",
            },
        ]
        lfm_tims = [tim for tim in tims if tim["match_number"] > 2]
        action_categories = self.test_calc.get_action_categories(tims)
        lfm_action_categories = self.test_calc.get_action_categories(lfm_tims)
        assert self.test_calc.calculate_modes(action_categories, lfm_action_categories) == {
            "mode_preloaded_gamepiece": ["CONE"],
            "mode_start_position": ["0"],
            "lfm_mode_start_position": ["0"],
            "mode_auto_charge_level": ["DOCK"],
            "lfm_mode_auto_charge_level": ["DOCK"],
            "mode_tele_charge_level": ["DOCK"],
            "lfm_mode_tele_charge_level": ["DOCK"],
        }

    def test_success_rates(self):
        team_data = {
            "matches_played": 5,
            "matches_scored_coop": 2,
            "auto_charge_attempts": 4,
            "auto_dock_successes": 1,
            "auto_engage_successes": 3,
            "tele_charge_attempts": 8,
            "tele_dock_successes": 2,
            "tele_engage_successes": 2,
            "tele_park_successes": 0,
            "lfm_auto_charge_attempts": 3,
            "lfm_auto_dock_successes": 1,
            "lfm_auto_engage_successes": 0,
            "lfm_tele_charge_attempts": 4,
            "lfm_tele_dock_successes": 1,
            "lfm_tele_engage_successes": 1,
            "lfm_tele_park_successes": 1,
        }
        assert self.test_calc.calculate_success_rates(team_data) == {
            "percent_matches_scored_coop": 0.4,
            "charge_percent_success": 0.6666666666666666,
            "lfm_charge_percent_success": 0.42857142857142855,
            "auto_charge_percent_success": 1,
            "lfm_auto_charge_percent_success": 0.3333333333333333,
            "tele_charge_percent_success": 0.5,
            "lfm_tele_charge_percent_success": 0.5,
            "auto_dock_percent_success": 0.25,
            "lfm_auto_dock_percent_success": 0.3333333333333333,
            "auto_engage_percent_success": 0.75,
            "lfm_auto_engage_percent_success": 0.0,
            "tele_dock_percent_success": 0.25,
            "lfm_tele_dock_percent_success": 0.25,
            "tele_engage_percent_success": 0.25,
            "lfm_tele_engage_percent_success": 0.25,
        }

    def test_calculate_average_points(self):
        team_data = {
            "auto_dock_successes": 4,
            "auto_engage_successes": 1,
            "tele_dock_successes": 2,
            "tele_engage_successes": 1,
            "tele_park_successes": 2,
        }
        assert self.test_calc.calculate_average_points(team_data) == {
            "tele_avg_charge_points": 7.3333333333333333,
            "auto_avg_charge_points": 8.8,
        }

    def test_calculate_sum_points(self):
        team_data = {
            "auto_avg_cone_low": 1,
            "tele_avg_cone_low": 2,
            "auto_avg_cone_mid": 3,
            "tele_avg_cone_mid": 1,
            "auto_avg_cone_high": 2,
            "tele_avg_cone_high": 3,
            "auto_avg_cube_low": 1,
            "tele_avg_cube_low": 2,
            "auto_avg_cube_mid": 3,
            "tele_avg_cube_mid": 1,
            "auto_avg_cube_high": 2,
            "tele_avg_cube_high": 3,
            "auto_charge_percent_success": 1,
            "tele_charge_percent_success": 2,
            "auto_avg_charge_points": 3.5,
            "tele_avg_charge_points": 1.5,
        }
        assert self.test_calc.calculate_sum_points(team_data) == {
            "avg_total_points": 104.5,
        }

    def test_run(self):
        """Tests run function from src/calculations/obj_team.py"""
        subj_tims = [
            {"match_number": 1, "team_number": "973", "scored_coop": True, "played_defense": True},
            {"match_number": 2, "team_number": "973", "scored_coop": True, "played_defense": True},
            {
                "match_number": 3,
                "team_number": "973",
                "scored_coop": False,
                "played_defense": False,
            },
            {
                "match_number": 1,
                "team_number": "1678",
                "scored_coop": False,
                "played_defense": True,
            },
            {"match_number": 2, "team_number": "1678", "scored_coop": True, "played_defense": True},
            {
                "match_number": 3,
                "team_number": "1678",
                "scored_coop": False,
                "played_defense": False,
            },
            {"match_number": 4, "team_number": "1678", "scored_coop": True, "played_defense": True},
            {
                "match_number": 5,
                "team_number": "1678",
                "scored_coop": False,
                "played_defense": False,
            },
        ]
        obj_tims = [
            # 973
            {
                "match_number": 1,
                "auto_cone_high": 15,
                "auto_cone_mid": 14,
                "auto_cone_low": 16,
                "auto_total_cones": 45,
                "auto_cube_high": 18,
                "auto_cube_mid": 14,
                "auto_cube_low": 3,
                "auto_total_cubes": 35,
                "tele_cone_high": 5,
                "tele_cone_mid": 10,
                "tele_cone_low": 4,
                "tele_total_cones": 19,
                "tele_cube_high": 10,
                "tele_cube_mid": 4,
                "tele_cube_low": 3,
                "tele_total_cubes": 17,
                "incap": 4,
                "confidence_rating": 30,
                "team_number": "973",
                "auto_charge_attempt": 1,
                "auto_charge_level": "ENGAGE",
                "tele_charge_attempt": 1,
                "tele_charge_level": "ENGAGE",
                "intakes_ground": 20,
                "intakes_station": 4,
                "intakes_low_row": 10,
                "total_intakes": 34,
                "tele_total_gamepieces_low": 7,
                "tele_total_gamepieces": 36,
                "auto_total_gamepieces_low": 19,
                "auto_total_gamepieces": 40,
                "preloaded_gamepiece": "CONE",
                "start_position": "2",
                "failed_scores": 4,
            },
            {
                "match_number": 2,
                "auto_cone_high": 6,
                "auto_cone_mid": 20,
                "auto_cone_low": 3,
                "auto_total_cones": 29,
                "auto_cube_high": 15,
                "auto_cube_mid": 13,
                "auto_cube_low": 18,
                "auto_total_cubes": 46,
                "tele_cone_high": 10,
                "tele_cone_mid": 20,
                "tele_cone_low": 30,
                "tele_total_cones": 60,
                "tele_cube_high": 14,
                "tele_cube_mid": 17,
                "tele_cube_low": 19,
                "tele_total_cubes": 50,
                "incap": 23,
                "confidence_rating": 58,
                "team_number": "973",
                "auto_charge_attempt": 1,
                "auto_charge_level": "ENGAGE",
                "tele_charge_attempt": 1,
                "tele_charge_level": "ENGAGE",
                "intakes_ground": 30,
                "intakes_station": 13,
                "intakes_low_row": 1,
                "total_intakes": 44,
                "tele_total_gamepieces_low": 49,
                "tele_total_gamepieces": 110,
                "auto_total_gamepieces_low": 21,
                "auto_total_gamepieces": 34,
                "preloaded_gamepiece": "CONE",
                "start_position": "1",
                "failed_scores": 5,
            },
            {
                "match_number": 3,
                "auto_cone_high": 1,
                "auto_cone_mid": 4,
                "auto_cone_low": 3,
                "auto_total_cones": 8,
                "auto_cube_high": 9,
                "auto_cube_mid": 3,
                "auto_cube_low": 6,
                "auto_total_cubes": 18,
                "tele_cone_high": 4,
                "tele_cone_mid": 3,
                "tele_cone_low": 7,
                "tele_total_cones": 14,
                "tele_cube_high": 13,
                "tele_cube_mid": 8,
                "tele_cube_low": 14,
                "tele_total_cubes": 35,
                "incap": 20,
                "confidence_rating": 18,
                "team_number": "973",
                "auto_charge_attempt": 1,
                "auto_charge_level": "DOCK",
                "tele_charge_attempt": 1,
                "tele_charge_level": "PARK",
                "intakes_ground": 1,
                "intakes_station": 23,
                "intakes_low_row": 14,
                "total_intakes": 38,
                "tele_total_gamepieces_low": 21,
                "tele_total_gamepieces": 49,
                "auto_total_gamepieces_low": 9,
                "auto_total_gamepieces": 12,
                "preloaded_gamepiece": "CUBE",
                "start_position": "1",
                "failed_scores": 6,
            },
            # 1678
            {
                "match_number": 1,
                "auto_cone_high": 13,
                "auto_cone_mid": 18,
                "auto_cone_low": 7,
                "auto_total_cones": 38,
                "auto_cube_high": 12,
                "auto_cube_mid": 7,
                "auto_cube_low": 5,
                "auto_total_cubes": 24,
                "tele_cone_high": 3,
                "tele_cone_mid": 9,
                "tele_cone_low": 3,
                "tele_total_cones": 15,
                "tele_cube_high": 10,
                "tele_cube_mid": 4,
                "tele_cube_low": 3,
                "tele_total_cubes": 17,
                "incap": 91,
                "confidence_rating": 100,
                "team_number": "1678",
                "auto_charge_attempt": 1,
                "auto_charge_level": "ENGAGE",
                "tele_charge_attempt": 1,
                "tele_charge_level": "DOCK",
                "intakes_ground": 24,
                "intakes_station": 35,
                "intakes_low_row": 12,
                "total_intakes": 71,
                "tele_total_gamepieces_low": 6,
                "tele_total_gamepieces": 32,
                "auto_total_gamepieces_low": 12,
                "auto_total_gamepieces": 20,
                "preloaded_gamepiece": "CONE",
                "start_position": "1",
                "failed_scores": 6,
            },
            {
                "match_number": 2,
                "auto_cone_high": 5,
                "auto_cone_mid": 3,
                "auto_cone_low": 9,
                "auto_total_cones": 15,
                "auto_cube_high": 4,
                "auto_cube_mid": 12,
                "auto_cube_low": 5,
                "auto_total_cubes": 21,
                "tele_cone_high": 9,
                "tele_cone_mid": 15,
                "tele_cone_low": 5,
                "tele_total_cones": 29,
                "tele_cube_high": 6,
                "tele_cube_mid": 1,
                "tele_cube_low": 0,
                "tele_total_cubes": 7,
                "incap": 34,
                "confidence_rating": 20,
                "team_number": "1678",
                "auto_charge_attempt": 1,
                "auto_charge_level": "ENGAGE",
                "tele_charge_attempt": 1,
                "tele_charge_level": "ENGAGE",
                "intakes_ground": 13,
                "intakes_station": 21,
                "intakes_low_row": 12,
                "total_intakes": 46,
                "tele_total_gamepieces_low": 5,
                "tele_total_gamepieces": 36,
                "auto_total_gamepieces_low": 14,
                "auto_total_gamepieces": 14,
                "preloaded_gamepiece": "CUBE",
                "start_position": "1",
                "failed_scores": 7,
            },
            {
                "match_number": 3,
                "auto_cone_high": 4,
                "auto_cone_mid": 12,
                "auto_cone_low": 0,
                "auto_total_cones": 16,
                "auto_cube_high": 14,
                "auto_cube_mid": 1,
                "auto_cube_low": 1,
                "auto_total_cubes": 16,
                "tele_cone_high": 3,
                "tele_cone_mid": 10,
                "tele_cone_low": 10,
                "tele_total_cones": 23,
                "tele_cube_high": 23,
                "tele_cube_mid": 4,
                "tele_cube_low": 3,
                "tele_total_cubes": 30,
                "incap": 21,
                "confidence_rating": 35,
                "team_number": "1678",
                "auto_charge_attempt": 1,
                "auto_charge_level": "DOCK",
                "tele_charge_attempt": 1,
                "tele_charge_level": "PARK",
                "intakes_ground": 3,
                "intakes_station": 51,
                "intakes_low_row": 2,
                "total_intakes": 56,
                "preloaded_gamepiece": "CONE",
                "tele_total_gamepieces_low": 13,
                "tele_total_gamepieces": 53,
                "auto_total_gamepieces_low": 1,
                "auto_total_gamepieces": 20,
                "start_position": "1",
                "failed_scores": 8,
            },
            {
                "match_number": 4,
                "auto_cone_high": 4,
                "auto_cone_mid": 5,
                "auto_cone_low": 10,
                "auto_total_cones": 19,
                "auto_cube_high": 9,
                "auto_cube_mid": 3,
                "auto_cube_low": 4,
                "auto_total_cubes": 16,
                "tele_cone_high": 9,
                "tele_cone_mid": 13,
                "tele_cone_low": 1,
                "tele_total_cones": 23,
                "tele_cube_high": 4,
                "tele_cube_mid": 9,
                "tele_cube_low": 1,
                "tele_total_cubes": 14,
                "incap": 12,
                "confidence_rating": 99,
                "team_number": "1678",
                "auto_charge_attempt": 1,
                "auto_charge_level": "ENGAGE",
                "tele_charge_attempt": 1,
                "tele_charge_level": "ENGAGE",
                "intakes_ground": 10,
                "intakes_station": 14,
                "intakes_low_row": 30,
                "total_intakes": 54,
                "tele_total_gamepieces_low": 2,
                "tele_total_gamepieces": 37,
                "auto_total_gamepieces_low": 14,
                "auto_total_gamepieces": 40,
                "preloaded_gamepiece": "CONE",
                "start_position": "1",
                "failed_scores": 6,
            },
            {
                "match_number": 5,
                "auto_cone_high": 1,
                "auto_cone_mid": 4,
                "auto_cone_low": 12,
                "auto_total_cones": 17,
                "auto_cube_high": 8,
                "auto_cube_mid": 10,
                "auto_cube_low": 12,
                "auto_total_cubes": 30,
                "tele_cone_high": 4,
                "tele_cone_mid": 8,
                "tele_cone_low": 3,
                "tele_total_cones": 15,
                "tele_cube_high": 12,
                "tele_cube_mid": 3,
                "tele_cube_low": 8,
                "tele_total_cubes": 23,
                "incap": 14,
                "confidence_rating": 54,
                "team_number": "1678",
                "auto_charge_attempt": 1,
                "auto_charge_level": "DOCK",
                "tele_charge_attempt": 1,
                "tele_charge_level": "DOCK",
                "intakes_ground": 5,
                "intakes_station": 31,
                "intakes_low_row": 16,
                "total_intakes": 52,
                "tele_total_gamepieces_low": 16,
                "tele_total_gamepieces": 38,
                "auto_total_gamepieces_low": 24,
                "auto_total_gamepieces": 12,
                "preloaded_gamepiece": "CUBE",
                "start_position": "1",
                "failed_scores": 8,
            },
        ]
        expected_results = [
            {
                "team_number": "973",
                # Averages
                "auto_avg_cone_high": 7.333333333333333,
                "auto_avg_cone_mid": 12.666666666666666,
                "auto_avg_cone_low": 7.333333333333333,
                "auto_avg_cone_total": 27.333333333333332,
                "auto_avg_cube_high": 14.0,
                "auto_avg_cube_mid": 10.0,
                "auto_avg_cube_low": 9.0,
                "auto_avg_cube_total": 33.0,
                "tele_avg_cone_high": 6.333333333333333,
                "tele_avg_cone_mid": 11.0,
                "tele_avg_cone_low": 13.666666666666666,
                "tele_avg_cone_total": 31.0,
                "tele_avg_cube_high": 12.333333333333334,
                "tele_avg_cube_mid": 9.666666666666666,
                "tele_avg_cube_low": 12.0,
                "tele_avg_cube_total": 34.0,
                "tele_avg_gamepieces": 65.0,
                "avg_incap_time": 15.666666666666666,
                "avg_intakes_ground": 17.0,
                "avg_intakes_station": 13.333333333333334,
                "avg_intakes_low_row": 8.333333333333334,
                "avg_total_intakes": 38.666666666666664,
                "tele_avg_gamepieces_low": 25.666666666666668,
                "auto_avg_gamepieces_low": 16.333333333333332,
                "auto_avg_gamepieces": 28.666666666666668,
                "avg_failed_scores": 5.0,
                # LFM Averages
                "lfm_auto_avg_cone_high": 7.333333333333333,
                "lfm_auto_avg_cone_mid": 12.666666666666666,
                "lfm_auto_avg_cone_low": 7.333333333333333,
                "lfm_auto_avg_cone_total": 27.333333333333332,
                "lfm_auto_avg_cube_high": 14.0,
                "lfm_auto_avg_cube_mid": 10.0,
                "lfm_auto_avg_cube_low": 9.0,
                "lfm_auto_avg_cube_total": 33.0,
                "lfm_auto_avg_gamepieces": 28.666666666666668,
                "lfm_tele_avg_cone_high": 6.333333333333333,
                "lfm_tele_avg_cone_mid": 11.0,
                "lfm_tele_avg_cone_low": 13.666666666666666,
                "lfm_tele_avg_cone_total": 31.0,
                "lfm_tele_avg_cube_high": 12.333333333333334,
                "lfm_tele_avg_cube_mid": 9.666666666666666,
                "lfm_tele_avg_cube_low": 12.0,
                "lfm_tele_avg_cube_total": 34.0,
                "lfm_tele_avg_gamepieces": 65.0,
                "lfm_tele_avg_gamepieces_low": 25.666666666666668,
                "lfm_auto_avg_gamepieces_low": 16.333333333333332,
                "lfm_avg_incap_time": 15.666666666666666,
                "lfm_avg_intakes_ground": 17.0,
                "lfm_avg_intakes_station": 13.333333333333334,
                "lfm_avg_intakes_low_row": 8.333333333333334,
                "lfm_avg_total_intakes": 38.666666666666664,
                "lfm_avg_failed_scores": 5.0,
                # Standard Deviations
                "auto_sd_cone_high": 5.792715732327589,
                "auto_sd_cone_mid": 6.599663291074443,
                "auto_sd_cone_low": 6.128258770283412,
                "auto_sd_cone_total": 15.15109090315135,
                "auto_sd_cube_high": 3.7416573867739413,
                "auto_sd_cube_mid": 4.96655480858378,
                "auto_sd_cube_low": 6.48074069840786,
                "auto_sd_cube_total": 11.51810169544733,
                "auto_sd_gamepieces": 12.036980056845191,
                "tele_sd_cone_high": 2.6246692913372702,
                "tele_sd_cone_mid": 6.97614984548545,
                "tele_sd_cone_low": 11.61416759345623,
                "tele_sd_cone_total": 20.607442021431645,
                "tele_sd_cube_high": 1.699673171197595,
                "tele_sd_cube_mid": 5.436502143433364,
                "tele_sd_cube_low": 6.683312551921141,
                "tele_sd_cube_total": 13.490737563232042,
                "tele_sd_gamepieces": 32.25936556516056,
                # Counts
                "auto_charge_attempts": 3,
                "auto_dock_successes": 1,
                "auto_engage_successes": 2,
                "tele_charge_attempts": 3,
                "tele_dock_successes": 0,
                "tele_engage_successes": 2,
                "tele_park_successes": 1,
                "position_zero_starts": 0,
                "position_one_starts": 2,
                "position_two_starts": 1,
                "position_three_starts": 0,
                "position_four_starts": 0,
                "matches_incap": 3,
                "matches_played": 3,
                # LFM Counts
                "lfm_position_zero_starts": 0,
                "lfm_position_one_starts": 2,
                "lfm_position_two_starts": 1,
                "lfm_position_three_starts": 0,
                "lfm_position_four_starts": 0,
                "lfm_auto_charge_attempts": 3,
                "lfm_auto_dock_successes": 1,
                "lfm_auto_engage_successes": 2,
                "lfm_tele_charge_attempts": 3,
                "lfm_tele_dock_successes": 0,
                "lfm_tele_engage_successes": 2,
                "lfm_tele_park_successes": 1,
                "lfm_matches_incap": 3,
                # Super Counts
                "matches_scored_coop": 2,
                "matches_played_defense": 2,
                # Extrema
                "auto_max_cone_high": 15,
                "auto_max_cone_mid": 20,
                "auto_max_cone_low": 16,
                "auto_max_cones": 45,
                "auto_max_cube_high": 18,
                "auto_max_cube_mid": 14,
                "auto_max_cube_low": 18,
                "auto_max_cubes": 46,
                "auto_max_gamepieces": 40,
                "tele_max_cone_high": 10,
                "tele_max_cone_mid": 20,
                "tele_max_cone_low": 30,
                "tele_max_cones": 60,
                "tele_max_cube_high": 14,
                "tele_max_cube_mid": 17,
                "tele_max_cube_low": 19,
                "tele_max_cubes": 50,
                "tele_max_gamepieces": 110,
                "max_incap": 23,
                "max_auto_charge_level": "ENGAGE",
                "max_tele_charge_level": "ENGAGE",
                # LFM Extrema
                "lfm_auto_max_cone_high": 15,
                "lfm_auto_max_cone_mid": 20,
                "lfm_auto_max_cone_low": 16,
                "lfm_auto_max_cones": 45,
                "lfm_auto_max_cube_high": 18,
                "lfm_auto_max_cube_mid": 14,
                "lfm_auto_max_cube_low": 18,
                "lfm_auto_max_cubes": 46,
                "lfm_auto_max_gamepieces": 40,
                "lfm_tele_max_cone_high": 10,
                "lfm_tele_max_cone_mid": 20,
                "lfm_tele_max_cone_low": 30,
                "lfm_tele_max_cones": 60,
                "lfm_tele_max_cube_high": 14,
                "lfm_tele_max_cube_mid": 17,
                "lfm_tele_max_cube_low": 19,
                "lfm_tele_max_cubes": 50,
                "lfm_tele_max_gamepieces": 110,
                "lfm_max_incap": 23,
                "lfm_max_auto_charge_level": "ENGAGE",
                "lfm_max_tele_charge_level": "ENGAGE",
                # Modes
                "mode_preloaded_gamepiece": ["CONE"],
                "mode_start_position": ["1"],
                "mode_auto_charge_level": ["ENGAGE"],
                "mode_tele_charge_level": ["ENGAGE"],
                # LFM Modes
                "lfm_mode_start_position": ["1"],
                "lfm_mode_auto_charge_level": ["ENGAGE"],
                "lfm_mode_tele_charge_level": ["ENGAGE"],
                # Success Rates
                "percent_matches_scored_coop": 0.6666666666666666,
                "charge_percent_success": 0.8333333333333334,
                "auto_charge_percent_success": 1.0,
                "tele_charge_percent_success": 0.6666666666666666,
                "auto_dock_percent_success": 0.3333333333333333,
                "auto_engage_percent_success": 0.6666666666666666,
                "lfm_auto_dock_percent_success": 0.3333333333333333,
                "lfm_auto_engage_percent_success": 0.6666666666666666,
                "lfm_tele_dock_percent_success": 0,
                "lfm_tele_engage_percent_success": 0.6666666666666666,
                "tele_dock_percent_success": 0,
                "tele_engage_percent_success": 0.6666666666666666,
                # LFM Success Rates
                "lfm_charge_percent_success": 0.8333333333333334,
                "lfm_auto_charge_percent_success": 1.0,
                "lfm_tele_charge_percent_success": 0.6666666666666666,
                # Average Points
                "tele_avg_charge_points": 10.0,
                "auto_avg_charge_points": 10.666666666666666,
                # Sum Points
                "avg_total_points": 491.666666666666666,
            },
            {
                "team_number": "1678",
                # Averages
                "auto_avg_cone_high": 5.4,
                "auto_avg_cone_mid": 8.4,
                "auto_avg_cone_low": 7.6,
                "auto_avg_cone_total": 21.0,
                "auto_avg_cube_high": 9.4,
                "auto_avg_cube_mid": 6.6,
                "auto_avg_cube_low": 5.4,
                "auto_avg_cube_total": 21.4,
                "auto_avg_gamepieces": 21.2,
                "tele_avg_cone_high": 5.6,
                "tele_avg_cone_mid": 11.0,
                "tele_avg_cone_low": 4.4,
                "tele_avg_cone_total": 21.0,
                "tele_avg_cube_high": 11.0,
                "tele_avg_cube_mid": 4.2,
                "tele_avg_cube_low": 3.0,
                "tele_avg_cube_total": 18.2,
                "tele_avg_gamepieces": 39.2,
                "tele_avg_gamepieces_low": 8.4,
                "auto_avg_gamepieces_low": 13.0,
                "avg_incap_time": 34.4,
                "avg_intakes_ground": 11.0,
                "avg_intakes_station": 30.4,
                "avg_intakes_low_row": 14.4,
                "avg_total_intakes": 55.8,
                "avg_failed_scores": 7.0,
                # LFM Averages
                "lfm_auto_avg_cone_high": 3.5,
                "lfm_auto_avg_cone_mid": 6.0,
                "lfm_auto_avg_cone_low": 7.75,
                "lfm_auto_avg_cone_total": 16.75,
                "lfm_auto_avg_cube_high": 8.75,
                "lfm_auto_avg_cube_mid": 6.5,
                "lfm_auto_avg_cube_low": 5.5,
                "lfm_auto_avg_cube_total": 20.75,
                "lfm_auto_avg_gamepieces": 21.5,
                "lfm_tele_avg_cone_high": 6.25,
                "lfm_tele_avg_cone_mid": 11.5,
                "lfm_tele_avg_cone_low": 4.75,
                "lfm_tele_avg_cone_total": 22.5,
                "lfm_tele_avg_cube_high": 11.25,
                "lfm_tele_avg_cube_mid": 4.25,
                "lfm_tele_avg_cube_low": 3.0,
                "lfm_tele_avg_cube_total": 18.5,
                "lfm_tele_avg_gamepieces": 41.0,
                "lfm_tele_avg_gamepieces_low": 9.0,
                "lfm_auto_avg_gamepieces_low": 13.25,
                "lfm_avg_incap_time": 20.25,
                "lfm_avg_intakes_ground": 7.75,
                "lfm_avg_intakes_station": 29.25,
                "lfm_avg_intakes_low_row": 15.0,
                "lfm_avg_total_intakes": 52.0,
                "lfm_avg_failed_scores": 7.25,
                # Standard Deviations
                "auto_sd_cone_high": 4.029888335921977,
                "auto_sd_cone_mid": 5.748043145279966,
                "auto_sd_cone_low": 4.127953488110059,
                "auto_sd_cone_total": 8.602325267042627,
                "auto_sd_cube_high": 3.4409301068170506,
                "auto_sd_cube_mid": 4.127953488110059,
                "auto_sd_cube_low": 3.6110940170535577,
                "auto_sd_cube_total": 5.276362383309167,
                "auto_sd_gamepieces": 9.927738916792686,
                "tele_sd_cone_high": 2.8,
                "tele_sd_cone_mid": 2.6076809620810595,
                "tele_sd_cone_low": 3.0724582991474434,
                "tele_sd_cone_total": 5.366563145999495,
                "tele_sd_cube_high": 6.6332495807108,
                "tele_sd_cube_mid": 2.6381811916545836,
                "tele_sd_cube_low": 2.756809750418044,
                "tele_sd_cube_total": 7.833262411026456,
                "tele_sd_gamepieces": 7.194442299441979,
                # Counts
                "auto_charge_attempts": 5,
                "auto_dock_successes": 2,
                "auto_engage_successes": 3,
                "tele_charge_attempts": 5,
                "tele_dock_successes": 2,
                "tele_engage_successes": 2,
                "tele_park_successes": 1,
                "position_zero_starts": 0,
                "position_one_starts": 5,
                "position_two_starts": 0,
                "position_three_starts": 0,
                "position_four_starts": 0,
                "matches_incap": 5,
                "matches_played": 5,
                # LFM Counts
                "lfm_auto_charge_attempts": 4,
                "lfm_auto_dock_successes": 2,
                "lfm_auto_engage_successes": 2,
                "lfm_tele_charge_attempts": 4,
                "lfm_tele_dock_successes": 1,
                "lfm_tele_engage_successes": 2,
                "lfm_tele_park_successes": 1,
                "lfm_position_zero_starts": 0,
                "lfm_position_one_starts": 4,
                "lfm_position_two_starts": 0,
                "lfm_position_three_starts": 0,
                "lfm_position_four_starts": 0,
                "lfm_matches_incap": 4,
                # Super Counts
                "matches_scored_coop": 2,
                "matches_played_defense": 3,
                # Extrema
                "auto_max_cone_high": 13,
                "auto_max_cone_mid": 18,
                "auto_max_cone_low": 12,
                "auto_max_cones": 38,
                "auto_max_cube_high": 14,
                "auto_max_cube_mid": 12,
                "auto_max_cube_low": 12,
                "auto_max_cubes": 30,
                "auto_max_gamepieces": 40,
                "tele_max_cone_high": 9,
                "tele_max_cone_mid": 15,
                "tele_max_cone_low": 10,
                "tele_max_cones": 29,
                "tele_max_cube_high": 23,
                "tele_max_cube_mid": 9,
                "tele_max_cube_low": 8,
                "tele_max_cubes": 30,
                "tele_max_gamepieces": 53,
                "max_incap": 91,
                "max_auto_charge_level": "ENGAGE",
                "max_tele_charge_level": "ENGAGE",
                # LFM Extrema
                "lfm_auto_max_cone_high": 5,
                "lfm_auto_max_cone_mid": 12,
                "lfm_auto_max_cone_low": 12,
                "lfm_auto_max_cones": 19,
                "lfm_auto_max_cube_high": 14,
                "lfm_auto_max_cube_mid": 12,
                "lfm_auto_max_cube_low": 12,
                "lfm_auto_max_cubes": 30,
                "lfm_auto_max_gamepieces": 40,
                "lfm_tele_max_cone_high": 9,
                "lfm_tele_max_cone_mid": 15,
                "lfm_tele_max_cone_low": 10,
                "lfm_tele_max_cones": 29,
                "lfm_tele_max_cube_high": 23,
                "lfm_tele_max_cube_mid": 9,
                "lfm_tele_max_cube_low": 8,
                "lfm_tele_max_cubes": 30,
                "lfm_tele_max_gamepieces": 53,
                "lfm_max_incap": 34,
                "lfm_max_auto_charge_level": "ENGAGE",
                "lfm_max_tele_charge_level": "ENGAGE",
                # Modes
                "mode_preloaded_gamepiece": ["CONE"],
                "mode_start_position": ["1"],
                "mode_auto_charge_level": ["ENGAGE"],
                "mode_tele_charge_level": ["DOCK", "ENGAGE"],
                # LFM Modes
                "lfm_mode_start_position": ["1"],
                "lfm_mode_auto_charge_level": ["ENGAGE", "DOCK"],
                "lfm_mode_tele_charge_level": ["ENGAGE"],
                # Success Rates
                "percent_matches_scored_coop": 0.4,
                "charge_percent_success": 0.9,
                "auto_charge_percent_success": 1.0,
                "tele_charge_percent_success": 0.8,
                "auto_dock_percent_success": 0.4,
                "auto_engage_percent_success": 0.6,
                "lfm_auto_dock_percent_success": 0.5,
                "lfm_auto_engage_percent_success": 0.5,
                "lfm_tele_dock_percent_success": 0.25,
                "lfm_tele_engage_percent_success": 0.5,
                "tele_dock_percent_success": 0.4,
                "tele_engage_percent_success": 0.4,
                # LFM Success Rates
                "lfm_charge_percent_success": 0.875,
                "lfm_auto_charge_percent_success": 1.0,
                "lfm_tele_charge_percent_success": 0.75,
                # Average Points
                "tele_avg_charge_points": 8.0,
                "auto_avg_charge_points": 10.4,
                # Sum Points
                "avg_total_points": 348.0,
            },
        ]
        self.test_server.db.insert_documents("obj_tim", obj_tims)
        self.test_server.db.insert_documents("subj_tim", subj_tims)
        self.test_calc.run()
        result = self.test_server.db.find("obj_team")
        assert len(result) == 2
        for document in result:
            del document["_id"]
            assert document in expected_results
            # Removes the matching expected result to protect against duplicates from the calculation
            expected_results.remove(document)
